name: Allure Aggregate Report

on:
  workflow_run:
    workflows: ["Registration Tests", "UI Tests", "API Tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  aggregate-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Registration Allure
        uses: actions/download-artifact@v4
        with:
          name: allure-registration
          path: allure-results/registration

      - name: Download UI Allure
        uses: actions/download-artifact@v4
        with:
          name: allure-ui
          path: allure-results/ui

      - name: Download API Allure
        uses: actions/download-artifact@v4
        with:
          name: allure-api
          path: allure-results/api

      - name: Generate combined Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy combined report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: all-tests
