name: Base test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  registration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and start container
        run: docker compose up -d --build

      - name: Run base test
        run: docker compose run --rm bot pytest tests/test_base --alluredir=allure-results

      - name: Stop containers
        run: docker compose down

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-base
          path: allure-results
