name: Registration Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  registration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and start container
        run: docker compose up -d --build

      - name: Run registration tests
        run: docker compose run --rm bot pytest tests/registration --alluredir=allure-results

      - name: Stop containers
        run: docker compose down

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: registration
